version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
  assignees:
      - "ivanshukhov"
  reviewers:
      - "ivanshukhov"
  labels:
  - dependencies
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
  assignees:
      - "ivanshukhov"
  reviewers:
      - "ivanshukhov"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
    time: "09:00"
  assignees:
      - "ivanshukhov"
  reviewers:
      - "ivanshukhov"
