name: Docs build
# This workflow runs when a PR is labeled with `docs`
# This will check if the docs build successfully by running `npm run build`
on:
  push:
    branches:
      - main
      - release/*

permissions: write-all
jobs:
  check-docs-build:
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            docs/**/*.sh
            docs/**/*.py
            docs/**/*.md
            docs/**/*.png
            docs/**/*.jpg
            docs/**/*.json
            docs/**/*.js
            x/**/*.md
      - name: Install dependencies and build docs 🧱
        run: |
          make build-docs
        # Check only if there are differences in the source code
        if: env.GIT_DIFF

      - name: Deploy to GH Pages 🚀
        if: env.GIT_DIFF
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist